id = "simple-darker"
name = "Simple Darker Theme"
description = "Simple Darker Theme for zed"
version = "0.0.1"
schema_version = 1
authors = ["David Pait <davidjpait@gmail.com>"]
repository = "https://github.com/DP19/zed-theme-simple-darker"
